### ISSUE TITLE
Convert Invalid literal for int()

### ISSUE THREAD

**Issue by resyst-it** [hswayne77/xenserver_to_xen#2]
Hello,

When i execute this command :

python xenmigrate.py --debug --convert=Ref:4/ apache-01.img

and i have this error.

traceback (most recent call last):
  File "xenmigrate.py", line 502, in <module>
    reftoraw(opts.convert,args[0],opts.gz)
  File "xenmigrate.py", line 319, in reftoraw
    numfiles=int(refdirlist[-2])
ValueError: invalid literal for int() with base 10: '00003808.checksum'

Could you help me to correct his ?

Regards.

**Comment by derekjhyang** [comment]
I guess maybe you lost something in your xva image :(

**Comment by resyst-it** [comment]
ok thank you.
